# Generated by Django 3.2.7 on 2021-09-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comic',
            name='img',
            field=models.TextField(max_length=500),
        ),
    ]
