# Generated by Django 3.2.7 on 2021-09-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='funkos',
            field=models.ManyToManyField(to='main_app.Funko'),
        ),
    ]
